export const AUTH = {
  LOGIN: {
    START: "LOGIN_START",
    SUCCESS: "LOGIN_SUCCESS",
    ERROR: "LOGIN_ERROR",
  },
  LOGOUT: {
    START: "LOGOUT_START",
    SUCCESS: "LOGOUT_SUCCESS",
    ERROR: "LOGOUT_ERROR",
  },
  REGISTER: {
    START: "REGISTER_START",
    SUCCESS: "REGISTER_SUCCESS",
    ERROR: "REGISTER_ERROR",
  },
};
